### PR TITLE
deps: update lnd to v0.17.0-beta

### PR DESCRIPTION
**Pull request by jbrill**
Updates the lnd bindings to reflect `v0.17.0-beta`

### CODE REVIEW

**Review by jamaljsr — COMMENTED** [review]
Would you mind also updating `loop` and `tapd` to the versions supported by LNC? It makes sense to update all of them at once. 

The LNC wasm-client [go.mod](https://github.com/lightninglabs/lightning-node-connect/blob/v0.2.8-alpha/cmd/wasm-client/go.mod#L9-L13) file contains the specific versions that are compatible.

**Comment by jbrill** [comment]
@jamaljsr thanks for the help! Was able to update the versions. I noticed the pool version seemed to be a bit inconsistent `v0.6.4-beta.0.20231003174306-80d8854a0c4b`, which was incompatible with the yarn generate command. I simply use `v0.6.4-beta` in this PR.

**Review by ViktorTigerstrom — APPROVED** [review]
Looks good to me :fire:!
Though I'd like to stress that I have never coded Typescript, and have very little web programming experience in general, so I don't know if you should depend on my review too heavily heh 😅! So please give @jamaljsr review much more weight.

> I noticed the pool version seemed to be a bit inconsistent v0.6.4-beta.0.20231003174306-80d8854a0c4b, which was incompatible with the yarn generate command. I simply use v0.6.4-beta in this PR.

I'd like to comment regarding this though, as that the plain pool `v0.6.4-beta` version does not include lnd version `v0.17.0-beta`. The inconsistent version is a version that Oli created that just adds lnd `v0.17.0-beta` to that release, until the next release is out. This is the version that we have added in LiT + LNC, so I think it would make sense to use the same version in LNC-core? Else when adding the new version of LNC, it'll require that dependency anyways? I also don't know if we get any unwanted side effects in LNC-core if we add a pool version that doesn't have lnd `v0.17.0-beta`, but then bump the lnd version that's used in LNC-core to `v0.17.0-beta`.

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 👌

**Pull request merged**
